export const TYPE_COLUMN_TABLE = {
  LABLE: "LABLE",
  INPUTTEXT: "INPUTTEXT",
  INPUTNUMBER:"INPUTNUMBER",
  DROPDOWN: "DROPDOWN",
  CHECKBOX: "CHECKBOX",
  IMAGE:"IMAGE",
  ACTION: "ACTION",
};

export const ACTION_TYPE_TABLE = {
  DELETE: "DELETE",
  UPDATE: "UPDATE",
  REFERENCE: "REFERENCE"
};